"""
embeddings_io.py — Embedding Output Contract
=============================================
Responsibilities:
  - Save embeddings to .npz with validated schema
  - Load embeddings from .npz with shape validation
  - Checkpoint partial results during pipeline run
  - Provide M2/M3 extension points without breaking M1 schema

Design decisions:
  - Single responsibility: this module only handles I/O. No model logic.
  - Schema is versioned — fields are never removed, only added.
  - Checkpointing saves every N batches so a crash costs at most
    checkpoint_every batches, not the full run.
  - numpy .npz is used over HDF5 for simplicity at <=10k samples.
    M3+ can swap to HDF5 by changing save/load here only.

Milestone compatibility:
  M1: image_embeddings, text_embeddings, ids, labels
  M2: + captions_generated, image_hidden_states (optional)
  M3: + bleu_scores, meteor_scores, cider_scores, rouge_l_scores (optional)
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import numpy as np

from src.utils import get_output_path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Schema definition
# ---------------------------------------------------------------------------

# M1 required keys — always present in a valid embeddings file
M1_REQUIRED_KEYS = {
    "image_embeddings",   # float32 [N, 512]
    "text_embeddings",    # float32 [N, 512]
    "ids",                # str     [N]
    "labels",             # str     [N]
}

# M2/M3 optional keys — present only when generated by those pipelines
OPTIONAL_KEYS = {
    "image_hidden_states",  # float32 [N, 197, 768] — M2 cross-attention
    "captions_generated",   # str     [N]            — M2 decoder output
    "bleu_scores",          # float32 [N]            — M3
    "meteor_scores",        # float32 [N]            — M3
    "cider_scores",         # float32 [N]            — M3
    "rouge_l_scores",       # float32 [N]            — M3
}

ALL_KNOWN_KEYS = M1_REQUIRED_KEYS | OPTIONAL_KEYS


# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------

def save_embeddings(
    image_embeddings: np.ndarray,
    text_embeddings:  np.ndarray,
    ids:              list[str],
    labels:           list[str],
    config:           dict[str, Any],
    output_path:      Path | None = None,
    **optional_arrays: np.ndarray,
) -> Path:
    """
    Save the M1 embedding schema to a .npz file.

    Validates shapes before writing. Raises ValueError if shapes are
    inconsistent rather than silently writing corrupt data.

    Args:
        image_embeddings : float32 array [N, D] — CLIP image embeddings
        text_embeddings  : float32 array [N, D] — GPT-2 text embeddings
        ids              : list of N image ID strings
        labels           : list of N class label strings
        config           : master config dict
        output_path      : override output path (default: from config)
        **optional_arrays: M2/M3 optional arrays keyed by schema name

    Returns:
        Path where the file was saved.
    """
    path = output_path or get_output_path(config)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    n = len(ids)
    _validate_save_inputs(image_embeddings, text_embeddings, ids, labels, n)

    save_dict = {
        "image_embeddings": image_embeddings.astype(np.float32),
        "text_embeddings":  text_embeddings.astype(np.float32),
        "ids":              np.array(ids,    dtype=object),
        "labels":           np.array(labels, dtype=object),
    }

    # Validate and add optional M2/M3 arrays
    for key, array in optional_arrays.items():
        if key not in ALL_KNOWN_KEYS:
            logger.warning("Unknown array key '%s' — saving anyway but not in schema", key)
        if len(array) != n:
            raise ValueError(
                f"Optional array '{key}' has length {len(array)}, "
                f"expected {n} to match ids."
            )
        save_dict[key] = array

    np.savez_compressed(path, **save_dict)

    logger.info(
        "Saved embeddings | path=%s | N=%d | image_shape=%s | text_shape=%s",
        path, n, image_embeddings.shape, text_embeddings.shape,
    )
    return path


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

def load_embeddings(
    path:   Path | str,
    config: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Load embeddings from a .npz file and validate M1 required keys.

    Args:
        path:   Path to .npz file.
        config: Optional master config for additional validation.

    Returns:
        dict with at minimum:
            image_embeddings : np.ndarray [N, D]
            text_embeddings  : np.ndarray [N, D]
            ids              : np.ndarray [N] (str)
            labels           : np.ndarray [N] (str)
        Plus any optional M2/M3 arrays present in the file.

    Raises:
        FileNotFoundError: If .npz file does not exist.
        ValueError:        If required keys are missing or shapes are invalid.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Embeddings file not found: {path}")

    data = np.load(path, allow_pickle=True)

    # Validate required keys
    missing = M1_REQUIRED_KEYS - set(data.files)
    if missing:
        raise ValueError(
            f"Embeddings file is missing required keys: {missing}\n"
            f"Found keys: {data.files}"
        )

    result = {key: data[key] for key in data.files}

    # Shape consistency check
    n = len(result["ids"])
    for key in M1_REQUIRED_KEYS:
        if len(result[key]) != n:
            raise ValueError(
                f"Shape mismatch: '{key}' has {len(result[key])} rows "
                f"but 'ids' has {n}."
            )

    # Verify image and text embeddings have matching dimensions.
    # We do NOT enforce a specific dimension here because the dimension
    # depends on the CLIP variant: ViT-B/32 → 512, ViT-L/14 → 768.
    img_dim  = result["image_embeddings"].shape[-1]
    text_dim = result["text_embeddings"].shape[-1]
    if img_dim != text_dim:
        logger.warning(
            "Dimension mismatch: image_embeddings=%d, text_embeddings=%d. "
            "Ensure both were produced by the same pipeline run.",
            img_dim, text_dim,
        )
    else:
        logger.info("Embedding dimension: %d (both image and text)", img_dim)

    logger.info(
        "Loaded embeddings | path=%s | N=%d | keys=%s",
        path, n, list(result.keys()),
    )
    return result


# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------

class EmbeddingCheckpointer:
    """
    Accumulates batches of embeddings and saves partial checkpoints
    every N batches to prevent data loss on crash.

    Usage:
        ckpt = EmbeddingCheckpointer(config)
        for batch in batches:
            image_embs, text_embs = model(batch)
            ckpt.add_batch(image_embs, text_embs, ids, labels)
        final_path = ckpt.finalize()
    """

    def __init__(self, config: dict[str, Any]) -> None:
        self.config           = config
        self.checkpoint_every = config["output"]["checkpoint_every"]
        self.output_path      = get_output_path(config)

        # Accumulators
        self._image_embs: list[np.ndarray] = []
        self._text_embs:  list[np.ndarray] = []
        self._ids:        list[str]         = []
        self._labels:     list[str]         = []
        self._batch_count = 0

        logger.info(
            "EmbeddingCheckpointer ready | checkpoint_every=%d | output=%s",
            self.checkpoint_every, self.output_path,
        )

    def add_batch(
        self,
        image_embeddings: np.ndarray,
        text_embeddings:  np.ndarray,
        ids:              list[str],
        labels:           list[str],
    ) -> None:
        """
        Add a batch of embeddings to the accumulator.
        Triggers a checkpoint save every checkpoint_every batches.
        """
        self._image_embs.append(image_embeddings)
        self._text_embs.append(text_embeddings)
        self._ids.extend(ids)
        self._labels.extend(labels)
        self._batch_count += 1

        if self._batch_count % self.checkpoint_every == 0:
            self._save_checkpoint()

    def _save_checkpoint(self) -> None:
        """Save current accumulator state as a checkpoint."""
        if not self._ids:
            return

        ckpt_path = self.output_path.parent / f"checkpoint_{len(self._ids)}.npz"

        save_embeddings(
            image_embeddings = np.concatenate(self._image_embs, axis=0),
            text_embeddings  = np.concatenate(self._text_embs,  axis=0),
            ids              = self._ids,
            labels           = self._labels,
            config           = self.config,
            output_path      = ckpt_path,
        )
        logger.info(
            "Checkpoint saved | N=%d | path=%s",
            len(self._ids), ckpt_path,
        )

    def finalize(self) -> Path:
        """
        Concatenate all accumulated batches and save the final output file.
        Removes intermediate checkpoints after successful final save.

        Returns:
            Path to the final saved .npz file.
        """
        if not self._ids:
            raise RuntimeError("No data accumulated — cannot finalize empty checkpoint.")

        final_path = save_embeddings(
            image_embeddings = np.concatenate(self._image_embs, axis=0),
            text_embeddings  = np.concatenate(self._text_embs,  axis=0),
            ids              = self._ids,
            labels           = self._labels,
            config           = self.config,
            output_path      = self.output_path,
        )

        # Clean up intermediate checkpoint files
        for ckpt_file in self.output_path.parent.glob("checkpoint_*.npz"):
            try:
                ckpt_file.unlink()
                logger.debug("Removed checkpoint: %s", ckpt_file)
            except OSError:
                pass

        logger.info(
            "Finalized | total_samples=%d | saved to %s",
            len(self._ids), final_path,
        )
        return final_path

    @property
    def accumulated_count(self) -> int:
        return len(self._ids)


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _validate_save_inputs(
    image_embeddings: np.ndarray,
    text_embeddings:  np.ndarray,
    ids:              list[str],
    labels:           list[str],
    n:                int,
) -> None:
    """Validate that all arrays are consistent before saving."""
    checks = {
        "image_embeddings": image_embeddings,
        "text_embeddings":  text_embeddings,
        "ids":              ids,
        "labels":           labels,
    }
    for name, arr in checks.items():
        if len(arr) != n:
            raise ValueError(
                f"'{name}' has length {len(arr)}, expected {n} to match ids."
            )

    if image_embeddings.ndim != 2:
        raise ValueError(
            f"image_embeddings must be 2D [N, D], got shape {image_embeddings.shape}"
        )
    if text_embeddings.ndim != 2:
        raise ValueError(
            f"text_embeddings must be 2D [N, D], got shape {text_embeddings.shape}"
        )